spring:
  datasource:
    url: jdbc:mysql://localhost:3306/t_schedule?serverTimezone=Asia/Seoul
    username: root
    password: yna51i1E@
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect

      hibernate:
        ddl-auto: create-drop  # (create, update, validate, none 가능)
        default_schema: public  # ✅ Hibernate 6.x에서는 기본 스키마를 명시해야 함
      show-sql : true
      properties:
        hibernate:
          format_sql: true  # ✅ SQL 문을 보기 쉽게 출력
          use_sql_comments: true  # ✅ SQL에 주석 추가      show-sql: true
  h2:
    console:
      enabled: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true


openai:
  api-key : "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"